version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    image: app
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - 3001:3000
    depends_on:
      - db

volumes:
  postgres:
